"""add_agent_logs_table

Revision ID: 80208e820e40
Revises: 7a8f15c812ad
Create Date: 2026-05-11 19:06:40.257360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80208e820e40'
down_revision: Union[str, None] = '7a8f15c812ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('normalized_query', sa.Text(), nullable=False),
    sa.Column('plan', sa.Text(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_logs_id'), 'agent_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_logs_id'), table_name='agent_logs')
    op.drop_table('agent_logs')
    # ### end Alembic commands ###
